# Site wide configuration

title: kmassada tech blog
locale: en_US
email: 'admin@kmassada.com'
description: 'Just another tech blog'

# Serving
url: 'http://127.0.0.1:4000'
bsaseurl: ''

# Jekyll configuration
permalink:   /:categories/:title/

# Conversion
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist

# Site owner
owner:
  name: Kenneth Massada
  avatar: bio-photo.jpg
  bio: "curious engineer seeking answers"
  email: "admin@kmassada.com"
  twitter: kmassada
  facebook: kmassada
  google:
    plus: KennethMassada
    analytics: UA-58957717-1
  github: kmassada
  stackoverflow: 1095800/kmassada
  linkedin: kennethmassada
  instagram: sndnjmz
twitter_username: kmassada
github_username:  kmassada