# Site settings
title: kmassada tech blog
email: admin@kmassada.com
description: > # this means to ignore newlines until "baseurl:"
  This is site is my personal exploration of the blogging platform jekyll
  with the hope to maybe sometime replace/delete all my previous github style
  how-tos, and incorporate them in a beautifully style, yet still very 
  technical or markdown oriented self-help pages
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.kmassada.com" # the base hostname & protocol for your site
twitter_username: kmassada
github_username:  kmassada

# Build settings
markdown: kramdown
