# Site wide configuration

title: kmassada tech blog
locale: en_US
url: 'http://127.0.0.1:4000'
bsaseurl: '/'
email: 'admin@kmassada.com'
description: ''
twitter_username: jekyllrb
github_username:  jekyll

# Jekyll configuration
permalink:   /:categories/:title/
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist

# Default extensions
post_ext: md
page_ext: md

# Format titles with titlecase?
titlecase: true

# Site owner
owner:
  name: Kenneth Massada
  avatar: bio-photo.jpg
  bio: ".."
  email: "admin@kmassada.com"
  twitter: kmassada
  facebook: kmassada
  google:
    plus: KennethMassada
    analytics: UA-58957717-1
  github: kmassada
  stackoverflow: 1095800/kmassada
  linkedin: kennethmassada
  instagram: sndnjmz